# Generated by Django 3.2.3 on 2021-09-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_diskspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiskSpace',
        ),
    ]
