# Generated by Django 3.2.3 on 2021-09-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_delete_diskspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
